/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.amf.eventmonitor.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Tracker service. Represents a row in the &quot;EventMonitor_Tracker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.amf.eventmonitor.model.impl.TrackerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.amf.eventmonitor.model.impl.TrackerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Tracker
 * @see com.liferay.amf.eventmonitor.model.impl.TrackerImpl
 * @see com.liferay.amf.eventmonitor.model.impl.TrackerModelImpl
 * @generated
 */
@ProviderType
public interface TrackerModel extends BaseModel<Tracker>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tracker model instance should use the {@link Tracker} interface instead.
	 */

	/**
	 * Returns the primary key of this tracker.
	 *
	 * @return the primary key of this tracker
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tracker.
	 *
	 * @param primaryKey the primary key of this tracker
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this tracker.
	 *
	 * @return the uuid of this tracker
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this tracker.
	 *
	 * @param uuid the uuid of this tracker
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the audit event ID of this tracker.
	 *
	 * @return the audit event ID of this tracker
	 */
	public long getAuditEventId();

	/**
	 * Sets the audit event ID of this tracker.
	 *
	 * @param auditEventId the audit event ID of this tracker
	 */
	public void setAuditEventId(long auditEventId);

	/**
	 * Returns the company ID of this tracker.
	 *
	 * @return the company ID of this tracker
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tracker.
	 *
	 * @param companyId the company ID of this tracker
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this tracker.
	 *
	 * @return the create date of this tracker
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this tracker.
	 *
	 * @param createDate the create date of this tracker
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the user ID of this tracker.
	 *
	 * @return the user ID of this tracker
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this tracker.
	 *
	 * @param userId the user ID of this tracker
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tracker.
	 *
	 * @return the user uuid of this tracker
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this tracker.
	 *
	 * @param userUuid the user uuid of this tracker
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tracker.
	 *
	 * @return the user name of this tracker
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this tracker.
	 *
	 * @param userName the user name of this tracker
	 */
	public void setUserName(String userName);

	/**
	 * Returns the client ip of this tracker.
	 *
	 * @return the client ip of this tracker
	 */
	@AutoEscape
	public String getClientIP();

	/**
	 * Sets the client ip of this tracker.
	 *
	 * @param clientIP the client ip of this tracker
	 */
	public void setClientIP(String clientIP);

	/**
	 * Returns the event type of this tracker.
	 *
	 * @return the event type of this tracker
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this tracker.
	 *
	 * @param eventType the event type of this tracker
	 */
	public void setEventType(String eventType);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Tracker tracker);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Tracker> toCacheModel();

	@Override
	public Tracker toEscapedModel();

	@Override
	public Tracker toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}